export default [
    {
        id: 1,
        title: "Pyramids of Giza",
        location: "Egypt",
        googleMapLink: "https://goo.gl/maps/kU4BuQtWDT14YANA6",
        startDate: "12 July, 2023",
        endDate: "15 July, 2023",
        description: "The Great Pyramid of Giza is the oldest and largest of the three pyramids in the Giza pyramid complex bordering present-day Giza in Greater Cairo, Egypt. It is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact.",
        image: "pyramids.jpg",
        imageAlt: "Pyramids of Giza",
    },
    {
        id: 2,
        title: "Istanbul",
        location: "Turkey",
        googleMapLink: "https://goo.gl/maps/8bkLvrYJvTdd9Wf47",
        startDate: "17 July, 2023",
        endDate: "25 July, 2023",
        description: "Istanbul is a major city in Turkey that straddles Europe and Asia across the Bosphorus Strait. Its Old City reflects cultural influences of the many empires that once ruled here.",
        image: "istanbul.jpg",
        imageAlt: "Istanbul",
    },
    {
        id: 3,
        title: "Venice",
        location: "Italy",
        googleMapLink: "https://goo.gl/maps/MEMfDB17q2RRx3tq7",
        startDate: "25 July, 2023",
        endDate: "30 July, 2023",
        description: "Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea.",
        image: "venice.jpg",
        imageAlt: "Venice",
    },
];
